version: "3.8"
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot-etc:/etc/letsencrypt
      - ./certbot-var:/var/lib/letsencrypt
    depends_on:
      - backend
      - frontend
    restart: always

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    depends_on: 
      - backend
    restart: always

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./backend/posts
        target: /app/posts
    restart: always
