version: "3.8"
services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    restart: always

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/posts:/app/posts
    ports:
      - "5000:5000"
    restart: always

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./frontend/build:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    restart: always
