version: "3.8"
services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    restart: always

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./backend/posts
        target: /app/posts
    ports:
      - "5000:5000"
    restart: always

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./frontend/build
        target: /usr/share/nginx/html
      - type: bind
        source: ./certbot/conf
        target: /etc/letsencrypt
      - type: bind
        source: ./certbot/www
        target: /var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    restart: always
